export const ACTIONS = {
  CREATE_EXTERNAL_ACCOUNT: "CREATE_EXTERNAL_ACCOUNT",
  NODE_REGISTERED: "NODE_REGISTERED",
  MINING_REWARD: "MINING_REWARD",
  INSTANT_MESSAGE: "INSTANT_MESSAGE",
  TRANSACTION_EXTERNAL_ACCOUNT: "TRANSACTION_EXTERNAL_ACCOUNT"
};
